config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "dashboard", to: "pages#dashboard"

  resources :users, only: [:show]

  resources :superstars do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [ :create ]
  end
  resources :bookings, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :superstar
  belongs_to :user
  validates :event_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :superstar
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/models/superstar.rb
class Superstar < ApplicationRecord
  has_many :bookings
  has_many :reviews
  belongs_to :user
  validates :name, presence: true
  validates :event_type, presence: true
  validates :bio, presence: true
  validates :price, presence: true
  validates :region, presence: true

  include PgSearch::Model
    pg_search_scope :search_by_name_and_event_type,
      against: [ :name, :event_type ],
      using: {
        tsearch: { prefix: true }
      }

  def self.event_type
    ["wedding", "birthday", "honeymoon", "party"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :superstars
  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_superstar, only: [:new, :create]
  before_action :set_booking, only: [:show]

  def show
  end

  def new
    @booking = Booking.new
    @review = Review.new
  end

  def create
    @superstar = Superstar.find(params[:superstar_id])
    @booking = Booking.new(booking_params)
    @booking.superstar = @superstar
    @booking.user = current_user

    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'superstars/show'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:event_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_superstar
    @superstar = Superstar.find(params[:superstar_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @superstars = Superstar.all
  end

  def dashboard
    @user = current_user
    @superstars = @user.superstars
    @bookings = @user.bookings
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @superstar = Superstar.find(params[:superstar_id])
    @review.superstar = @superstar
    if @review.save
      redirect_to superstar_path(@superstar.id)
    else
      render superstar_path(@superstar.id)
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/superstars_controller.rb
class SuperstarsController < ApplicationController

  def index
    if params[:query].present?
      @superstars = Superstar.search_by_name_and_event_type(params[:query])
    else
      @superstars = Superstar.all
    end
    # if params[:button] && params[:query] != "" && Superstar.all.event_type.include?(params[:query])
    #   @superstars = Superstar.all.select { |superstar| superstar.event_type.downcase.include?(params[:query].downcase) }
    # elsif params[:button] && params[:query] != ""
    #   @superstars = Superstar.all.select { |superstar| superstar.name.downcase.include?(params[:query].downcase) }
    # else
    #   @superstars = Superstar.all
    # end
  end

  def show
    @superstar = Superstar.find(params[:id])
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @superstar = Superstar.new
  end

  def create
    @superstar = Superstar.new(superstar_params)
    @superstar.user = current_user
    if @superstar.save!
      redirect_to superstars_path, alert: "Hello"
    else
      render :new
    end
  end

  private

  def superstar_params
    params.require(:superstar).permit(:name, :event_type, :bio, :price, :image_url, :region)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="banner">
  <div class="container">
    <h2> Congratulations!</h2>
    <h3>You will have <%=@superstar.name%> join you at your <%=@superstar.event_type%>!</h3>
    <br>
    <br>
    <h4>TOTAL PRICE €<%=@superstar.price%></h4>
    <br>
    Thanks for choosing Celebritify!
    <br>
    <%= link_to 'Find other Superstars', superstars_path, class:'btn btn-primary'%>
  </div>
</div>

app/views/bookings/show.html.erb
  <div class="congratulations-banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1607499457689-3fd1ac3ffcdd?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2940&q=80);">
    <div class="container text-center">
      <h1 >Congratulations🎉</h1>
      <br>
      <br>
      <br>
      <h2>You will have <%=@booking.superstar.name%> join you at your <%=@booking.superstar.event_type%></h2>
      <br>
      <br>
      <h3>Total Price €<%=@booking.superstar.price%></h3>
      <br>
      <br>
      <h4>Thanks for choosing Celebritify!</h4>
      <br>
      <%= link_to 'Find other Superstars', superstars_path, class:'btn btn-dark'%>
      <br>
    </div>
  </div>

    <%# <div class="container">
    <h1 class="text-center mb-5">Featured</h1> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Celebritify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container d-flex justify-content-end">
  <%= link_to 'Create Superstar', new_superstar_path, class:'btn btn-dark mr-3 mt-5 mb-5'%>
  <%= link_to 'Book a Superstar', superstars_path, class:'btn btn-dark mt-5 mb-5'%>
</div>

<div class="container container-dashboard mb-5">

  <div class="dashboard-section">
    <h3>My Superstars</h3>
      <div class="">
        <% if @user.superstars.exists? %>
          <% @superstars.each do |superstar| %>
            <div class="card mt-4" style="width: 18rem;">
              <%= image_tag superstar.image_url, class: "card-img-top" %>
              <div class="card-body">
                <div class="card-title">
                  <h5><%= superstar.name  %></h5>
                  <p class="card-text"> <%= superstar.event_type %> </p>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>No superstars created yet.</p>
        <% end %>
      </div>
    </div>

  <div class="dashboard-section">
    <h3> My Bookings</h3>
      <div class="">
        <% if @user.bookings.exists? %>
          <% @bookings.each do |booking| %>
            <div class="card mt-4" style="width: 18rem;">
              <%= image_tag booking.superstar.image_url, class: "card-img-top" %>
              <div class="card-body">
                <div class="card-title">
                  <h5><%= booking.superstar.name %></h5>
                  <p class="card-text"> <%= booking.superstar.event_type %> </p>
                  <p class="card-text"> <%= booking.event_date %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>No bookings created yet.</p>
        <% end %>
      </div>
  </div>

</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.8)), url(https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80);">
  <div class="container">
    <h1 class="mb-5 homepage">Find a celebrity to attend your event</h1>
    <%= link_to 'Starhunt', superstars_path, class:'btn home-starhunt'%>
    <%= link_to 'Create Star', new_superstar_path, class:'btn home-create'%>
  </div>
</div>

<br>
<br>


<h1 class="container text-center mb-5 homepagetitle">Featured</h1>
<div class="container d-flex justify-content-center" >
  <div class="d-flex justify-content-center">
    <div class="row">
      <% @superstars.first(3).each do |superstar| %>
        <div class="card mr-5" style="width: 18rem;">
          <%= image_tag superstar.image_url, class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= superstar.name.upcase %></h5>
            <p class="card-text"> <%= superstar.event_type.capitalize %> </p>
            <%= link_to 'Pick Me!', superstar, class:"btn confirm-pick"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>
<br>


<div class="container">
<%= link_to superstars_path(utf8: "✓" , :query => "wedding", button: ""), style: "text-decoration: none;" do %>
  <div class="card-category mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1770&q=80)">
    Wedding
  </div>
<% end %>
<%= link_to superstars_path(utf8: "✓" , :query => "birthday", button: ""), style: "text-decoration: none;" do %>
  <div class="card-category mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1502035618526-6b2f1f5bca1b?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8YmlydGhkYXl8ZW58MHwwfDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    Birthday
  </div>
<% end %>
<%= link_to superstars_path(utf8: "✓" , :query => "honeymoon", button: ""), style: "text-decoration: none;" do %>
    <div class="card-category mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1576158831003-d41033ec31fd?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2940&q=80)">
    Honeymoon
  </div>
<% end %>
<%= link_to superstars_path(utf8: "✓" , :query => "party", button: ""), style: "text-decoration: none;" do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1571456331030-a1369bc759dc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80)">
    Party
  </div>
<% end %>
<br>
<br>
  <div class="d-flex justify-content-center mb-5">
  <%= link_to 'ALL SUPERSTARS ☞', superstars_path, class:'btn btn-rgba'%>
  </div>
</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright text-center">
    @Copyright Celebritify 2021
  </div>
   <div class="footer-socialmedia">
      <div class="fbicon">
        <%= image_tag 'https://logodix.com/logo/939279.png'%>
      </div>
      <div class="twicon">
        <%= image_tag 'https://logodix.com/logo/1049774.png'%>
      </div>
    </div>
</div>


<%# .fbicon, .twicon, .pticon %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
    <h1 class=navbar-title>CELEBRITIFY</h1>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Starhunt", superstars_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Superstar", new_superstar_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars.githubusercontent.com/u/18228670?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/superstars/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1595422656453-90448f373188?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80);">
  <div class="container w-50">
    <%= form_tag superstars_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find your Superstar..."
        %>
      <br>
      <p class= "search-text"><%= submit_tag "Search", class: "btn confirm-pick" %></p>
    <% end %>
  </div>
</div>


  <h1 class="page-title text-center mt-5 indexpagetitle">All SuperStars</h1>
  <h4 class ="secondary-title text-center mt-2 indexpagesecondtitle"> Pick one to star in your super event!</h4>

  <br>

  <br>

  <div class="container">
    <div class="d-flex">
      <div class="row justify-content-between">
          <% @superstars.each do |superstar| %>
            <div class="card" style="width: 18rem;">
              <%= image_tag superstar.image_url, class: "card-img-top" %>
              <div class="card-body">
                <h5 class="card-title"><%= superstar.name.upcase %></h5>
                <p class="card-text"> <%= superstar.event_type.capitalize %> </p>
                <%= link_to 'Pick Me!', superstar, class:"btn confirm-pick"%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <br>
  <br>
  <br>

</div>

app/views/superstars/new.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1607499457689-3fd1ac3ffcdd?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2940&q=80); color:white;">
<div class="container d-flex justify-content-center w-50">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="mt-5">Create a superstar profile</h1>
      <%= simple_form_for @superstar do |f| %>
        <%= f.input :name %>
        <%= f.input :event_type %>
        <%= f.input :bio %>
        <%= f.input :price %>
        <%= f.input :region %>
        <%= f.input :image_url %>
        <%= f.submit class: 'btn btn-dark mt-3 mb-5' %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/superstars/show.html.erb
  <div class="show-body">
  <div class="container container-show d-flex justify-content-between left-text">
    <div>
    <h4 class="booking-title mb-4"> <%= @superstar.name.upcase %>
    </h4>
        <%= image_tag @superstar.image_url, class: "avatar-large mb-4", alt: "avatar-large" %>
        <p class="showpage-texts"> <strong>Event Type:</strong> <%= @superstar.event_type.capitalize %></p>
        <p class="showpage-texts"><strong>Bio:</strong> <%= @superstar.bio %></p>
        <h2 class="showpage-texts"><strong>Price: </strong>€ <%= @superstar.price %></h2>
      <p class="showpage-texts"><strong>Available in:</strong> <%= @superstar.region %></p>
    <br>
        <%= link_to '← Back to Starhunt', superstars_path, class: " go-back-arrow"%>
    </div>

  <div>
  <div class ="forms-right">
    <h4 class =showpage-texts><strong>When will <%= @superstar.name %> attend your <%= @superstar.event_type%>?</strong>
      <%= simple_form_for([@superstar, @booking]) do |f| %>
        <%= f.input :event_date %> </h4>
      <br>
          <p><%= f.submit "BOOK SUPERSTAR", class: 'btn confirm-book' %></p>
        <% end %>
    <br>
    <br>
    <br>
    <br>
    <br>
    </div>
  </div>
  </div>
  <div class="container center-review">
  <h4 style="text-align:center" class="review-text mb-4 mt-5">Review <%= @superstar.name %>'s Services:</h4>
  </div>

  <div class="container">
  <%= simple_form_for [@superstar, @review] do |f| %>
    <p class =review-mini-texts><%= f.input :content, label_html: { class:"text-input-white"} %>
    <%= f.input :rating, label_html: { class:"text-input-white"} %></p>
    </div>
      <div class="container center-review">
      <%= f.submit class: 'btn confirm-review' %>
      </div>
  <% end %>

<br>

<div class="container center-review">
<h4 class="review-text mb-4">Previous Reviews</h4>
</div>
<div class=container>
  <ul class="list-group">
  <% @superstar.reviews.each do |review| %>
    <li class="list-group-item mb-3">
      <%= review.content %>
      <%= review.rating %>
    </li>
  <% end %>
  </ul>
  <br>
</div>